"""T03 Wave B feedback lifecycle, persistence, and T02 sidecar bridge."""

from app.feedback.errors import (
    CorruptFeedbackSnapshot,
    FeedbackConflict,
    FeedbackError,
    FeedbackErrorCode,
    FeedbackNotFound,
    FeedbackPermissionDenied,
    FeedbackStorageError,
    FingerprintConflict,
    IdempotencyConflict,
    InvalidFeedbackInput,
    LineageNotFound,
    UnsafeFeedbackInput,
    UnsupportedFeedbackSchema,
)
from app.feedback.migration import (
    import_legacy_feedback,
    migrate_legacy_feedback,
    migrate_legacy_feedback_payload,
)
from app.feedback.revision import (
    FeedbackPromptAdapter,
    RevisionExecutionMetadata,
    RevisionFeedbackContext,
    RevisionFeedbackContextBuilder,
    RevisionLineageConsumer,
    RevisionLineageHandoff,
    RevisionLineageHandoffEvent,
    RevisionPromptAdapter,
)
from app.feedback.service import (
    AllowAllFeedbackAuthorizer,
    DefaultFeedbackService,
    DenyAllFeedbackAuthorizer,
    FeedbackAuthorizer,
    FeedbackService,
    FeedbackSubmission,
)
from app.feedback.storage import FeedbackStore, SQLiteFeedbackStore

__all__ = [
    "AllowAllFeedbackAuthorizer",
    "CorruptFeedbackSnapshot",
    "DefaultFeedbackService",
    "DenyAllFeedbackAuthorizer",
    "FeedbackAuthorizer",
    "FeedbackConflict",
    "FeedbackError",
    "FeedbackErrorCode",
    "FeedbackNotFound",
    "FeedbackPermissionDenied",
    "FeedbackPromptAdapter",
    "FeedbackService",
    "FeedbackStorageError",
    "FeedbackStore",
    "FeedbackSubmission",
    "FingerprintConflict",
    "IdempotencyConflict",
    "InvalidFeedbackInput",
    "LineageNotFound",
    "RevisionExecutionMetadata",
    "RevisionFeedbackContext",
    "RevisionFeedbackContextBuilder",
    "RevisionLineageConsumer",
    "RevisionLineageHandoff",
    "RevisionLineageHandoffEvent",
    "RevisionPromptAdapter",
    "SQLiteFeedbackStore",
    "UnsafeFeedbackInput",
    "UnsupportedFeedbackSchema",
    "import_legacy_feedback",
    "migrate_legacy_feedback",
    "migrate_legacy_feedback_payload",
]
